name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate the snake
        uses: Platane/snk@master
        with:
          github_user_name: your-github-username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check repository status
        run: git status

      - name: Commit and push changes
        run: |
          git config --global user.name "shivani2825"
          git config --global user.email "jainshivani285@gmail.com"
          git add .
          git commit -m "Update contribution graph"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: dist
